class AppImage {
  AppImage._();
  static const kLogoImage = 'assets/images/logo_tala.png';
  static const kTalaImage = 'assets/images/Tala.png';
  static const kOnboardingLogo = 'assets/images/onboarding_logo.png';
  static const kAppleIcon = 'assets/images/apple_icon.svg';
  static const kGoogleIcon = 'assets/images/google_icon.svg';
  static const kPersonPicture = 'assets/images/profile_picture.svg';
  static const kOnboarding2 = 'assets/images/onboarding2.jpg';
  static const kOnboarding1 = 'assets/images/onboarding1.jpg';
  static const kPassionGaming = 'assets/images/gaming_icon.svg';
  static const kPassionTravel = 'assets/images/travel_icon.svg';
  static const kPassionDance = 'assets/images/dance_icon.svg';
  static const kPassionArts = 'assets/images/arts_icon.svg';
  static const kHomeIcon = 'assets/images/home_icon.svg';
  static const kChatIcon = 'assets/images/chat_icon.svg';
  static const kProfileIcon = 'assets/images/profile_icon.svg';
  static const kPassionNature = 'assets/images/nature_icon.svg';
  static const kPassionConcert = 'assets/images/concert_icon.svg';
  static const kPassionMusic = 'assets/images/music_icon.svg';
  static const kPassionPhotography = 'assets/images/photography_icon.svg';
  static const kMashbakIcon = 'assets/images/mashbak_icon.svg';
  static const kImageTalaOnboarding1 = 'assets/images/Rectangle 615.png';
  static const kImageTalaOnboarding2 = 'assets/images/Rectangle 616.png';
  static const kImageTalaOnboarding3 = 'assets/images/Rectangle 617.png';
  static const kImageTalaOnboarding4 = 'assets/images/Rectangle 694.png';
  static const kImageIslam = 'assets/images/islam.png';
  static const kImageTest = 'assets/images/test.jpg';
  static const kTalaLogoNav = 'assets/images/tala_button.png';
  static const kTalaLogoNavHover = 'assets/images/tala_button_hover.png';
  static const kHeartIcon = 'assets/images/heart_icon.svg';
}
